cache:
  paths:
  - node_modules/

stages:
  - clean
  - build
  - deploy

clean:
  stage: clean
  script:
  - docker network prune -f

build:
  stage: build
  script:
  - docker-compose build

deploy:
  stage: deploy
  script:
  - docker-compose down --remove-orphans
  - docker-compose up -d