version: "2"
services:
  app:
    build: .
    links:
      - mysql:mysql
    ports:
      - 4850:4850
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: mgc70
      MYSQL_PASSWORD: arou__nd11.5andround
      MYSQL_DATABASE: mgc70

